const ACTION_LOAD_LIVE_PRICES = 'ACTION_LOAD_LIVE_PRICES';
const ACTION_DISPLAY_LIVE_PRICES = 'ACTION_DISPLAY_LIVE_PRICES';

export default {
  Actions: {
    LoadLivePrices: ACTION_LOAD_LIVE_PRICES,
    DisplayLivePrices: ACTION_DISPLAY_LIVE_PRICES
  }
};